name: Self-Hosted Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "EMAIL_API_KEY=${{ secrets.EMAIL_API_KEY }}" > .env

      - name: Stop and remove old container
        run: |
          docker-compose down
          docker rm -f netflex-api-prod || true

      - name: Build and run new container
        env:
          EMAIL_API_KEY: ${{ secrets.EMAIL_API_KEY }}
        run: docker-compose up -d --build