name: Self-Hosted Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        uses: actions/checkout@v3

      - name: Stop and clean old containers
        run: docker-compose down

      - name: Build and run new containers
        run: docker-compose up -d --build
